// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}


// Validate ../../../RAGScope/frontend/app/benchmarks/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/benchmarks">> = Specific
  const handler = {} as typeof import("../../../RAGScope/frontend/app/benchmarks/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../RAGScope/frontend/app/benchmarks/questions/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/benchmarks/questions/[id]">> = Specific
  const handler = {} as typeof import("../../../RAGScope/frontend/app/benchmarks/questions/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../RAGScope/frontend/app/benchmarks/versions/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/benchmarks/versions/[id]">> = Specific
  const handler = {} as typeof import("../../../RAGScope/frontend/app/benchmarks/versions/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../RAGScope/frontend/app/comparisons/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/comparisons">> = Specific
  const handler = {} as typeof import("../../../RAGScope/frontend/app/comparisons/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../RAGScope/frontend/app/corpora/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/corpora/[id]">> = Specific
  const handler = {} as typeof import("../../../RAGScope/frontend/app/corpora/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../RAGScope/frontend/app/datasets/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/datasets/[id]">> = Specific
  const handler = {} as typeof import("../../../RAGScope/frontend/app/datasets/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../RAGScope/frontend/app/datasets/compare/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/datasets/compare">> = Specific
  const handler = {} as typeof import("../../../RAGScope/frontend/app/datasets/compare/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../RAGScope/frontend/app/datasets/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/datasets">> = Specific
  const handler = {} as typeof import("../../../RAGScope/frontend/app/datasets/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../RAGScope/frontend/app/documents/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/documents/[id]">> = Specific
  const handler = {} as typeof import("../../../RAGScope/frontend/app/documents/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../RAGScope/frontend/app/laboratory/[runId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/laboratory/[runId]">> = Specific
  const handler = {} as typeof import("../../../RAGScope/frontend/app/laboratory/[runId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../RAGScope/frontend/app/laboratory/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/laboratory">> = Specific
  const handler = {} as typeof import("../../../RAGScope/frontend/app/laboratory/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../RAGScope/frontend/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../../RAGScope/frontend/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../RAGScope/frontend/app/runtime/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/runtime">> = Specific
  const handler = {} as typeof import("../../../RAGScope/frontend/app/runtime/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../RAGScope/frontend/app/versions/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/versions/[id]">> = Specific
  const handler = {} as typeof import("../../../RAGScope/frontend/app/versions/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}







// Validate ../../../RAGScope/frontend/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../RAGScope/frontend/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
